tasks:
  - init: pip3 install -r requirements/test.txt

image: gitpod/workspace-postgres

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
