tasks:
  - name: Pip install
    init: pip3 install -r requirements/test.txt && gp sync-done pip
  - name: Generate Data
    init: gp sync-await pip
    command: python python/generate_events.py && gp sync-done generate-events
  - name: Setup DB
    init: gp ports await 5432
    command: psql -f sql/setup_db.sql && gp sync-done db-setup
  - name: Insert Data
    init: gp sync-await db-setup && gp sync-await generate-events
    command: |
      psql -c "\copy website_visits from 'data/website_data.csv' DELIMITER ',' CSV HEADER"
      psql -c "\copy employees from 'data/employees.csv' DELIMITER ',' CSV HEADER"

image: gitpod/workspace-postgres

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
